Comments
vyomea/CMPUT404-project-socialdistribution pull request #113
Opened 2022-04-03 19:56 UTC by Sutanshu

Bunch of comments, and individually liked
![Screen Shot 2022-04-03 at 1 47 35 PM (2)](https://user-images.githubusercontent.com/42788023/161445745-0ffa1bde-1f93-4903-b0bd-e1be1c357935.png)

Adding a comment, will make this prettier in the next design PR
![Screen Shot 2022-04-03 at 1 47 55 PM (2)](https://user-images.githubusercontent.com/42788023/161445753-7ca43c97-4e82-44e6-9d58-9057ca8978d0.png)

Added comment, also fixed navBar css
![Screen Shot 2022-04-03 at 1 50 26 PM (2)](https://user-images.githubusercontent.com/42788023/161445774-86f91733-8382-49e8-97aa-9bd57f3b6b33.png)

2022-04-03 20:24 UTC, osmani2 requested changes

2022-04-03 20:24 UTC, osmani2 commented on src/app/src/App.tsx
> +        <Route path="/authors/:id/posts/:id" element={<Comments currentUser={currentUser} />} />
This looks like the backend route. We wanted the frontend route to just be `path="/post/:postId"` where you can see the post and all it's comments.

2022-04-03 20:24 UTC, osmani2 commented on src/app/src/components/UserPost.tsx
> +      `/authors/${props?.postAuthor?.id.split("/").pop()}/posts/${props?.post?.id}/comments`,
Same issue here.
This looks like the backend route. We wanted the frontend route to just be `path="/post/:postId"` where you can see the post and all it's comments.

2022-04-03 20:24 UTC, osmani2 commented on src/app/src/components/UserPost.tsx
> +              <CommentsContainer onClick={navigateToComments}>
Can we change the cursor style to a pointer when hovering

2022-04-03 20:24 UTC, osmani2 commented on src/app/src/pages/Mainpage.tsx
> -      <NavBarContainer>
Can we do this for the other pages, or were you planning on that in your design PR?
<img width="1280" alt="Screen Shot 2022-04-03 at 2 24 13 PM" src="https://user-images.githubusercontent.com/55111012/161447013-981e17ae-5246-4f66-b8c7-1106d32e39e9.png">

2022-04-03 20:46 UTC, kylemclean requested changes

2022-04-03 20:46 UTC, kylemclean commented on src/app/src/pages/Comments.tsx
> +  const authorID = url.split("/")[2];
Use `useParams()` instead.
https://reactrouter.com/docs/en/v6/api#useparams

2022-04-03 21:14 UTC, osmani2 commented on src/app/src/App.tsx
> +        <Route path="/authors/:id/posts/:id" element={<Comments currentUser={currentUser} />} />
@Sutanshu I think I was unclear with this, sorry. I DON'T want this to look like a backend route. It is the frontend and route and needs to be exactly `/profile/:authorId/post/:postId`

2022-04-03 21:16 UTC, osmani2 commented on src/app/src/components/UserPost.tsx
> +      `/authors/${props?.postAuthor?.id.split("/").pop()}/posts/${props?.post?.id}/comments`,
@Sutanshu Same here again, should be of the form /profile/${props?.postAuthor?.id.split("/").pop()}/post/${props?.post?.id}` same as App.tsx

2022-04-03 21:42 UTC, osmani2 requested changes

2022-04-03 21:42 UTC, osmani2 commented on src/app/src/pages/Comments.tsx
> +        .withId(authorID)
We'd want the currentUser to create the comment. Not the authorID one, that's who'se post we're commenting on.

2022-04-03 21:42 UTC, osmani2 commented on src/app/src/pages/Comments.tsx
> +        <UserPost post={post} likes={5} currentUser={currentUser} postAuthor={currentUser} />
We want the authorID author as postAuthor (use authorID to get author), we're not always commenting on our own posts.

2022-04-04 00:28 UTC, osmani2 approved these changes

2022-04-04 00:28 UTC, merged